### ISSUE TITLE
Unexpected keyword argument 'enable_temporal_attentions'

### ISSUE THREAD

**Issue by alfredplpl** [hotshotco/Hotshot-XL#1]
I would like to an animation by my model, so I run the code:
```bash
python inference.py   --prompt="anime style, anime artworks, a girl is smiling"   --output="output.gif" --pretrained_path='/home/username/github/emi'
```

Then, I got the error:
```python
Traceback (most recent call last):
  File "inference.py", line 191, in <module>
    main()
  File "inference.py", line 171, in main
    images = pipe(args.prompt,
  File "/home/username/github/Hotshot-XL/venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/github/Hotshot-XL/hotshot_xl/pipelines/hotshot_xl_pipeline.py", line 825, in __call__
    noise_pred = self.unet(
  File "/home/username/github/Hotshot-XL/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'enable_temporal_attentions'
```

How can I fix it?

**Comment by alfredplpl** [comment]
FYI: I can generate the animation by your model.
![output](https://github.com/hotshotco/Hotshot-XL/assets/3625196/cdddcc27-2a67-4f6a-b726-1115c5831d98)

**Comment by aakashs** [comment]
awesome @alfredplpl - could you please post how you resolved your issue for others' future reference?

**Comment by alfredplpl** [comment]
@aakashs Sorry, this is made by the default model. So, I wanna make know how to make the model.

**Comment by alfredplpl** [comment]
I misunderstand this repository. That wrote it. So, I run the command:
```bash
python inference.py   --prompt="anime style, anime artworks, a girl is smiling"   --output="output.gif" --spatial_unet_base='/home/username/github/emi_anime/unet'
```
Then, I got my animation by my model.
![output](https://github.com/hotshotco/Hotshot-XL/assets/3625196/8f9e77c5-24f0-4e6d-b2bf-1694fa2126b9)

Thanks again.
The issue will be closed.
